export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAIL = 'GET_ARTICLES_FAIL';
export const LOADING = 'LOADING';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const SET_PAGINATION_FILTERS = 'SET_PAGINATION_FILTERS';